-- 1.LIST ALL MANAGER DATA
SELECT * FROM EMP WHERE JOB='MANAGER';

-- 2.LIST EMP WHO ARE WORKING AS MANAGER OR ANALYST OR CLERK
SELECT ENAME FROM EMP WHERE JOB='MANAGER' OR JOB='ANALYST' OR JOB='CLERK';

-- 3.LIST EMP WHO ARE EARNING SAL BETWEEN 3000 AND 5000 (INCLUSIVE OF LIMIT)
SELECT ENAME FROM EMP WHERE SAL>=3000 AND SAL <=5000;

-- 4.LIST EMP WHO ARE WORKING AS MANAGER OR ANALYST OR CLERK AND EARNING SAL BETWEEN 3000 AND 5000
SELECT ENAME FROM EMP WHERE SAL>=3000 AND SAL <=5000 AND JOB='MANAGER' OR JOB='ANALYST' OR JOB='CLERK';

-- 5.LIST ALL EMP WHE ARE EARNING COMM
SELECT ENAME FROM EMP WHERE COMM;

-- 6.LIST ALL EMP WHOSE COMM IS NOT NULL
SELECT ENAME FROM EMP WHERE COMM IS NOT NULL;

-- 7.LIST ALL EMP WHOSE NAME STARTS WITH S
SELECT ENAME FROM EMP WHERE ENAME LIKE 'S%';

-- 8.LIST ALL EMP WHOSE NAME ENDS WITH R
SELECT ENAME FROM EMP WHERE ENAME LIKE '%R';

-- 9.LIST ALL EMP WHOSE NAME CONTAINS A
SELECT ENAME FROM EMP WHERE ENAME LIKE '%A%';

-- 10.LIST ALL EMP WHOSE NAME CONTAINS A AS SECOND LETTER
SELECT ENAME FROM EMP WHERE ENAME LIKE '%A%';

-- 11. LIST ALL EMP WHOSE NAME STARTS WITH EITHER M OR S
SELECT ENAME FROM EMP WHERE ENAME LIKE '%M' OR ENAME LIKE '%S';

-- 12.LIST ALL EMP WHOSE NAME STARTS BETWEEN A TO M
SELECT * FROM EMP WHERE ENAME>='%A' AND ENAME<='%M';

-- 13. LIST ALL EMP WHOSE NAME CONTAINS _
 SELECT ENAME FROM EMP WHERE ENAME LIKE='%_%';

-- 14. LIST ALL EMP WHO ARE WORKING AS MANAGER IN EITHER DEPT 10 OR 20 AND ALL CLERK FOR DEPT3 30
 SELECT ENAME FROM EMP WHERE (JOB='MANAGER' AND (DEPTNO='10' OR DEPTNO='20')) OR (JOB='CLERK' AND DEPTNO='30');

-- 15. LIST ENAME, SAL AND BONUS AS 10% OF SALARY
SELECT ENAME,SAL,0.1*SAL AS 'BONUS' FROM EMP;

-- 16. LIST EMP DATA AS PER THE ASCENDING ORDER OF NAME
 SELECT ENAME FROM EMP ORDER BY ENAME ASC;

-- 17. LIST ALL AS PER THEIR SALARY HIGHES TO LOWEST
 SELECT * FROM EMP ORDER BY SAL DESC;

-- 18. LIST EMP AS PER THEIR DEPT, WITH IN DEPT HIGHEST TO LOWESET SAL
 SELECT EMPNO,ENAME,DEPTNO,SAL FROM EMP ORDER BY DEPTNO, SAL DESC;

-- 19. list top 3 highest paid emp
 SELECT * FROM EMP ORDER BY SAL DESC LIMIT 0,3;

-- 20. RETURN SEQUENTIAL NUMBER RETURN RANK BASED ON SPECIFED CRITERIA IF TWO EMP HAVE SAME SALARY THEY BOTH GET SAME NUMBER AND NEXT NUMBER WILL BE SKIPPED
SELECT EMPNO,ENAME,DEPTNOSAL,RANK() OVER (PARTITION BY DEPTNO ORDER BY SAL DESC) AS 'RANK' FROM EMP;

-- 21.RETURN CONSECUTIVE RANKING VALUES BASED ON A SPECIFIED CRITERIA
SELECT EMPNO,ENAME,DEPTNO,SAL,
DENSE_RANK() OVER(partition by DEPTNO ORDER BY SAL DESC) AS 'RANK' FROM EMP;

-- 22.LIST THE DIFFERNT JOB NAME
 SELECT JOB FROM EMP GROUP BY JOB;

-- 23.LIST TOTAL ORGANIZATION SALARY
SELECT SUM(SAL) FROM EMP;

-- 24.LIST DEPTWISE TOTAL SALARY
SELECT SUM(SAL),DEPTNO FROM EMP GROUP BY DEPTNO;

-- 25.LIST JOBWISE EMP COUNT.
 SELECT JOB, COUNT(EMPNO) FROM EMP GROUP BY JOB;

-- 26.LIST ALL EMP WHO HAVE JOINED IN MONTH OF FEB
 SELECT ENAME FROM EMP WHERE MONTHNAME(HIREDATE)='FEBRUARY';

-- 27.LIST EMP COUNT JOINED BETWEEN 1981 AND 1983
SELECT ENAME,HIREDATE FROM EMP WHERE HIREDATE>='1981-01-01 00:00:00' AND HIREDATE<'1984-01-01 00:00:00';
 

-- 28.LIST HOW MANY YEARS OF SERVICE COMPLETED BY EACH EMP ARRANGE BASED ON TENURE HIGHEST TO LOWEST
SELECT ENAME,MONTH(CURRENT_DATE)-MONTH(HIREDATE) AS 'TENURE' FROM EMP ORDER BY TENURE DESC; 


